.Dd May 31, 2021
.Dt HYENA 7
.Os
.Sh NAME
.Nm hyena
.Nd randomized file delivery spotted butler
.Sh DESCRIPTION
.Nm
is a CGI and FastCGI interface for randomized file delivery over the internet.
.Sh INSTALLING
.Nm
targets FreeBSD, OpenBSD and (hopefully) Linux, and requires
.Lk https://kristaps.bsd.lv/kcgi/ kcgi
and
.Lk https://hyperrealm.github.io/libconfig/ libconfig
.Ns .
.
.Bd -literal -offset indent
\&./configure
make
make install
.Ed
.Pp
On FreeBSD and OpenBSD,
.Nm
is statically linked to make it easy to run in
.Xr chroot 2
.Ns .
.Sh DEPLOYMENT
.Nm
automatically detects if it's being run as a CGI or FastCGI worker.
.Pp
.Nm
can be configured using a configuration file commonly located at
.Pa /usr/local/etc/hyena/hyena.conf
.Pp
The configuration file provided in the source tree can be
used as an example, as it provides all the possible options the program can
be configured with.
.Ss nginx
Use
.Xr kfcgi 8
to run
.Nm
.Ns :
.Bd -literal -offset indent
kfcgi -u www -s /var/run/hyena.sock \e
	-U www -p /usr/local/www \e
	-- /usr/local/bin/hyena
.Ed
.Pp
Configure
.Xr nginx 8
to serve
.Nm
at the desired location, for example:
.Bd -literal -offset indent
location / {
	fastcgi_pass unix:/var/run/hyena.sock
	fastcgi_split_path_info (/)(.*);
	fastcgi_param PATH_INFO $fastcgi_path_info;
	include fastcgi_params;
}
.Ed
.Ss OpenBSD httpd
Use
.Xr kfcgi 8
to run
.Nm
.Ns :
.Bd -literal -offset indent
kfcgi -u www -s /var/www/run/hyena.sock \e
	-U www -p /usr/local/www \e
	-- /usr/local/bin/hyena
.Ed
.Pp
Configure
.Xr httpd 8
to serve
.Nm
at the desired location, for example:
.Bd -literal -offset indent
location "/*" {
	request strip 1
	fastcgi socket "/run/hyena.sock"
}
.Ed
.
.Sh AUTHORS
.An wolf Aq Mt wolf@fastmail.co.uk
